### ISSUE TITLE
Could not install dependencies

### ISSUE THREAD

**Issue by RockmanR** [embark-framework/embark-create-react-dapp-template#2]
I've tried to install the react template using the command "embark new embark-react --template create-react-dapp", but then I got:

`Installing template from https://github.com/embark-framework/embark-create-react-dapp-template/tree/4.0
Downloading template...
Download failed, response code 404
Retrying with the default branch...
It may not be compatible with your Embark version 4.0.2
Installing template from https://github.com/embark-framework/embark-create-react-dapp-template
Downloading template...
Installing packages...
Could not install dependencies. Try running `npm install` inside the project directory. 
Init complete

App ready at embark-react
`

Then when I get to the folder and type 'npm install' as suggested, I get the following:
`npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for embarkjs-connector-web3@4.0.0-beta.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'embark-react'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ahmedalmutawa/.npm/_logs/2019-05-18T20_58_37_480Z-debug.log`

Could you please tell me if I'm doing something wrong.

I'll be happy to provide any extra info if needed.

Thanks for the great work guys.

**Comment by RockmanR** [comment]
Alright, I've fixed it by updating the "embarkjs-connector-web3" version to "4.1.0-beta.1" in the package.json file.

**Comment by jrainville** [comment]
Good catch. We forgot to update the dependency. If you want, you can use version `4.0.0` instead since you don't seem to be using Embark's 4.1.beta yet, but it should still work so it's fine.

We'll update the dependency in a few.

**Comment by jrainville** [comment]
Issue shouldn't happen anymore since this was merged: https://github.com/embark-framework/embark-create-react-dapp-template/pull/1
